codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: no
comment: no
coverage:
  status:
    project:
      default:
        target: 0%
        threshold: 0.02%
    patch: no
ignore:
  - "3rdParty"
  - "SourceT"
